### ISSUE TITLE
Save Deck Object 

### ISSUE THREAD

**Issue by phoenixffire** [COSC481W-2021Fall/capstone-7-Deadly-Bugs#23]
As a user, I want to be able to save my deck to the database, so that I may load it for use wherever I have access to the database.

**Acceptance Guidelines:**
Be able to save a deck object to the database from the program

**Tasks:**
- [ ] Create an interactable button to save on the edit page.
- [ ]  Create a method that takes the deck object, turns it into json for storage.
- [ ] Then have the method save the deck to an open deck ID.
